### ISSUE TITLE
Python 3.12 compatibility: distutils is no longer available

### ISSUE THREAD

**Issue by hvbtup** [NaturalHistoryMuseum/pylibdmtx#102]
Maybe it's time to remove support for dmtx version < 0.75 and remove the if statements.

distutils (and distutils.LooseVersion) are no longer available on Python 3.12:

>>> from pylibdmtx import pylibdmtx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\.venv\Lib\site-packages\pylibdmtx\pylibdmtx.py", line 10, in <module>
    from .wrapper import (
  File "...\.venv\Lib\site-packages\pylibdmtx\wrapper.py", line 8, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

**Comment by danalex7212** [comment]
how do we solve this issue ?

**Comment by hvbtup** [comment]
I suppose to remove the if statements including the version check and to support newer dmtx versions only.

**Comment by xjpf** [comment]
You might want to get libdmtx0a or libdmtx0b

**Comment by JuR-0** [comment]
Duplicate of #99 and MR opened in #90
