### ISSUE TITLE
Windows 10 `Could not find module 'libdmtx-64.dll' (or one of its dependencies)`

### ISSUE THREAD

**Issue by eeintech** [NaturalHistoryMuseum/pylibdmtx#64]
* Python 3.9
* Running in virtual environment inside Git Bash

Traceback:
``` bash
Traceback (most recent call last):
  File "C:\Users\(edited)\env-labels\lib\site-packages\pylibdmtx\dmtx_library.py", line 51, in load
    libdmtx = cdll.LoadLibrary(fname)
  File "C:\Python\Python39\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libdmtx-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\(edited)\product_label.py", line 5, in <module>
    from pylibdmtx.pylibdmtx import encode, decode
  File "C:\Users\(edited)\env-labels\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\(edited)\env-labels\lib\site-packages\pylibdmtx\pylibdmtx.py", line 10, in <module>
    from .wrapper import (
  File "C:\Users\(edited)\env-labels\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\(edited)\env-labels\lib\site-packages\pylibdmtx\wrapper.py", line 70, in <module>
    _dmtxVersion = libdmtx_function('dmtxVersion', c_char_p)
  File "C:\Users\(edited)\env-labels\lib\site-packages\pylibdmtx\wrapper.py", line 58, in libdmtx_function
    return prototype((fname, load_libdmtx()))
  File "C:\Users\(edited)\env-labels\lib\site-packages\pylibdmtx\wrapper.py", line 39, in load_libdmtx
    LIBDMTX = dmtx_library.load()
  File "C:\Users\(edited)\env-labels\lib\site-packages\pylibdmtx\dmtx_library.py", line 53, in load
    libdmtx = cdll.LoadLibrary(str(Path(__file__).parent.joinpath(fname)))
  File "C:\Python\Python39\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\(edited)\env-labels\lib\site-packages\pylibdmtx\libdmtx-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

Tried to add:
``` python 
import os
os.add_dll_directory(os.getcwd())
```

Before `libdmtx = cdll.LoadLibrary(str(Path(__file__).parent.joinpath(fname)))` to no success.
Even tried to add the exact path to `libdmtx-64.dll` but did not work.

Was `libdmtx-64.dll` built on Windows 10?
Which are the dependencies I would need to install?

Thanks!

**Comment by eeintech** [comment]
Found an already built DLL that works 😃 

[libdmtx_64bit.zip](https://github.com/NaturalHistoryMuseum/pylibdmtx/files/7228161/libdmtx_64bit.zip)

Enjoy!

**Comment by xjpf** [comment]
pylibdmtx 0.1.10 from PyPi  - provided with this dll
pylibdmtx 0.1.11 from https://github.com/NaturalHistoryMuseum/pylibdmtx.git - providing no dll
So solution is:
- Install 1st one
- Get dll out
- Reinstall pylibdmtx with newest one
- Put dll back

**Comment by dyseg** [comment]
In my case, it was actually the depencency of the `libdmtx-64.dll` which was missing. It requries Microsoft Visual C++ 2013 Redistributable. If it is fine for you, just install it.
But I did not want to install that, so instead I recompiled the [libdmtx](https://github.com/dmtx/libdmtx) from source, targeting newer C++ runtime.
If anyone needs it (v0.7.8):

[libdmtx-64.zip](https://github.com/user-attachments/files/20977410/libdmtx-64.zip)
