### ISSUE TITLE
(Ubuntu) ImportError: Unable to find dmtx shared library

### ISSUE THREAD

**Issue by pecd** [NaturalHistoryMuseum/pylibdmtx#74]
Hi, everyone!

I run this code on my Ubuntu 20.04.3 LTS:

`from pylibdmtx.pylibdmtx import encode`

and get the following error:

```
/home/petr/Documents/PycharmProjects/Gitlab_test_3/myvenv/bin/python3.9 /home/petr/Documents/PycharmProjects/Gitlab_test_3/test_03.py
Traceback (most recent call last):
  File "/home/petr/Documents/PycharmProjects/Gitlab_test_3/test_03.py", line 1, in <module>
    from pylibdmtx.pylibdmtx import encode
  File "/home/petr/Documents/PycharmProjects/Gitlab_test_3/myvenv/lib/python3.9/site-packages/pylibdmtx/pylibdmtx.py", line 10, in <module>
    from .wrapper import (
  File "/home/petr/Documents/PycharmProjects/Gitlab_test_3/myvenv/lib/python3.9/site-packages/pylibdmtx/wrapper.py", line 70, in <module>
    _dmtxVersion = libdmtx_function('dmtxVersion', c_char_p)
  File "/home/petr/Documents/PycharmProjects/Gitlab_test_3/myvenv/lib/python3.9/site-packages/pylibdmtx/wrapper.py", line 58, in libdmtx_function
    return prototype((fname, load_libdmtx()))
  File "/home/petr/Documents/PycharmProjects/Gitlab_test_3/myvenv/lib/python3.9/site-packages/pylibdmtx/wrapper.py", line 39, in load_libdmtx
    LIBDMTX = dmtx_library.load()
  File "/home/petr/Documents/PycharmProjects/Gitlab_test_3/myvenv/lib/python3.9/site-packages/pylibdmtx/dmtx_library.py", line 47, in load
    raise ImportError('Unable to find dmtx shared library')
ImportError: Unable to find dmtx shared library

Process finished with exit code 1
```

**Comment by MathijsNL** [comment]
This should fix your issue.

```
sudo apt install libdmtx0b
```
